model:
  target: Models.interpretable_diffusion.gaussian_diffusion.Diffusion_TS
  params:
    seq_length: 608
    feature_size: 21
    n_layer_enc: 4
    n_layer_dec: 3
    d_model: 144  # 8 X 24
    timesteps: 1000
    sampling_timesteps: 1000
    loss_type: 'l1'
    beta_schedule: 'cosine'
    n_heads: 6
    mlp_hidden_times: 4
    attn_pd: 0.0
    resid_pd: 0.0
    kernel_size: 7
    padding_size: 3

solver:
  base_lr: 1.0e-5
  max_epochs: 1500
  results_folder: ./Checkpoints/weather_96
  gradient_accumulate_every: 4
  save_cycle: 150  # max_epochs // 10
  ema:
    decay: 0.995
    update_interval: 10
  
  scheduler:
    target: engine.lr_sch.ReduceLROnPlateauWithWarmup
    params:
      factor: 0.5
      patience: 200
      min_lr: 1.0e-5
      threshold: 1.0e-1
      threshold_mode: rel
      warmup_lr: 8.0e-4
      warmup: 100 
      verbose: False

dataloader:
  train_dataset:
    target: Utils.Data_utils.tail_dataset.TailDataset
    params:
      name: weather
      proportion: 1.0  # Set to rate < 1 if training conditional generation
      data_root: ./Data/datasets/tail_samples_weather_0_96.csv
      window: 608  # seq_length
      save2npy: True
      neg_one_to_one: True
      seed: 123
      period: train

  test_dataset:
    target: Utils.Data_utils.tail_dataset.TailDataset
    params:
      name: weather
      proportion: 0.9  # rate
      data_root: ./Data/datasets/tail_samples_weather_0_96.csv
      window: 608  # seq_length
      save2npy: True
      neg_one_to_one: True
      seed: 123
      period: test
      style: separate
      distribution: geometric
    coefficient: 1.0e-2
    step_size: 5.0e-2
    sampling_steps: 250

  batch_size: 64
  sample_size: 256
  shuffle: True